# Book Recommender System - Render Deployment Configuration
# Live URL: https://books-recommender-sscz.onrender.com/
services:
  - type: web
    name: book-recommender
    runtime: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
